## Exp 1

In [2]:
n=int(input("Enter the number of digits:"))
if n>0:
    number=int(input(f"Enter a {n}-digit integer:"))
    if number>=10**(n-1) and number<10**n:
        for i in range(n):
            digit=number//(10**(n-1))
            print(digit)
            number%=10**(n-1)
            n-=1
    else:
         print(f"Please enter a {n}-digit integer")
else:
    print("Please enter a valid number of digits(greater than 0)")

Enter the number of digits:3
Enter a 3-digit integer:123
1
2
3


## Exp 2

In [7]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
c=int(input("Enter the third number:"))
d=int(input("Enter the fourth number:"))
if a>b:a,b=b,a
if c>d:c,d=d,c
if a>c:a,c=c,a
if b>d:b,d=d,b
if b>c:b,c=c,b
print("The sorted number are:",a,b,c,d)

Enter the first number:8
Enter the second number:4
Enter the third number:7
Enter the fourth number:2
The sorted number are: 2 4 7 8


## Exp 4

In [9]:
number=int(input("Enter an n-digit number:"))
original_number=number
reversed_number=0
while number>0:
    digit=number%10
    reversed_number=reversed_number*10+digit
    number//=10
if original_number==reversed_number:
    print("Palindrome")
else:
    print("Not a palindrome")

Enter an n-digit number:34543
Palindrome


## Exp 5

In [11]:
n=int(input("enter an integer for multiplication table:"))
print(f'Multiplication table for {n}:')
for i in range(1,11):
    result=n*i
    print(f"{n}x{i}={result}")
    

enter an integer for multiplication table:6
Multiplication table for 6:
6x1=6
6x2=12
6x3=18
6x4=24
6x5=30
6x6=36
6x7=42
6x8=48
6x9=54
6x10=60


## Exp 3

In [11]:
n=int(input("Enter the number of elements:"))
numbers=[int(input(f"Enter number {i+1}:")) for i in range(n)]
mean=sum(numbers)/n
numbers.sort()
if n%2==0:
    median=(numbers[n//2-1]+numbers[n//2])/2
else:
    median=(numbers[n//2])
frequency={num:numbers.count(num) for num in numbers}
max_count=max(frequency.values())
mode=[k for k,v in frequency.items() if v==max_count]
if len(mode)==n:
    mode="No mode"
mean_difference_squared_sum=sum((x-mean)**2 for x in numbers)
variance_sample=mean_difference_squared_sum/(n-1) if n>1 else 0
variance_population=mean_difference_squared_sum/n
std_deviation_sample=variance_sample**0.5
std_deviation_population=variance_population**0.5
std_deviation=variance_population**0.5
print(f"Mean:{mean}")
print(f"Median:{median}")
print(f"Mode:{mode}")
print(f"Sample variance:{variance_sample}")
print(f"Population variance:{variance_population}")
print(f"Sample standard deviation:{std_deviation_sample}")
print(f"Population standard deviation:{std_deviation_population}")

             

Enter the number of elements:6
Enter number 1:3
Enter number 2:4
Enter number 3:5
Enter number 4:6
Enter number 5:8
Enter number 6:9
Mean:5.833333333333333
Median:5.5
Mode:No mode
Sample variance:5.366666666666667
Population variance:4.472222222222222
Sample standard deviation:2.316606713852541
Population standard deviation:2.1147629234082532


## Exp 6

In [3]:
number=int(input("Enter the integer number:"))
revs_number=0
while(number>0):
    remainder=number%10
    revs_number=(revs_number*10)+remainder
    number=number//10
print("The reverse number is :{}".format(revs_number))

Enter the integer number:253
The reverse number is :352


## Exp 7

In [6]:
def interchange_digits(number,pos1,pos2):
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int(''.join(number_list))
    return interchanged_number
number=int(input('Enter the user input:'))
pos1=int(input('Enter the 1st position which you want to swap:'))
pos2=int(input('Enter the 2nd position which you want to swap:'))
interchanged_number=interchange_digits(number,pos1,pos2)
print("Original numner:",number)
print("Interchanged number:",interchanged_number)


Enter the user input:56789
Enter the 1st position which you want to swap:1
Enter the 2nd position which you want to swap:4
Original numner: 56789
Interchanged number: 86759


## EXP 8

In [6]:
def capitalize_strings(string_list):
    return[s.capitalize() for s in string_list]
input_strings=['hello','good','how','simple']
capitalized_string=capitalize_strings(input_strings)
print(capitalized_string)

['Hello', 'Good', 'How', 'Simple']


## EXP 9

In [14]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={}
    for word in words:
        word=word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
    duplicates={word:count for word,count in word_count.items() if count>1}
    if duplicates:
        print("Duplicate words and their counts")
        for word,count in duplicates.items():
            print(f"{word}:{count}")
    else:
        print("No duplicate words found")
sentence=input("Enter a sentence")
count_duplicate_words(sentence)

Enter a sentenceA big black bug bit a big black dog
Duplicate words and their counts
a:2
big:2
black:2


## EXP 10:

In [2]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("Numpy array")
print(data)
print("-----------------------------")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("Row Sum")
print(totalr)
print("Column Sum")
print(totalc)
print("-----------------------------")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("Row mean")
print(meanr)
print("Column mean")
print(meanc)
print("-----------------------------")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("Row STD")
print(stdr)
print("Column STD")
print(stdc)


Numpy array
[[1 2 3]
 [4 5 6]]
-----------------------------
Row Sum
[ 6 15]
Column Sum
[5 7 9]
-----------------------------
Row mean
[2. 5.]
Column mean
[2.5 3.5 4.5]
-----------------------------
Row STD
[0.81649658 0.81649658]
Column STD
[1.5 1.5 1.5]


## EXP 11

In [6]:
import csv
file=open('Sample.csv',mode='r')
csv_reader=csv.reader(file,delimiter=',')
line_count=0
for row in csv_reader:
    if line_count==0:
        print(f'Coloumn names are {",".join(row)}')
        line_count+=1
    else:
        print(f'\t{row[0]} works in the {row[1]} department and was born in {row[2]}')
        line_count+=1
print(f'Processed {line_count} lines.')
file.close()

Coloumn names are Name,Department,Birthday_month
	Dhanya works in the AIML department and was born in March
	Akshaya works in the AIML department and was born in April
Processed 3 lines.


## Exp:12

In [13]:
import pandas as pd
def read_html_to_dict(html_file):
    tables=pd.read_html(html_file)
    tables_dict={}
    for i,table in enumerate(tables):
        table_dict=table.to_dict(orient='list')
        tables_dict[f'Tables_{i+1}']=table_dict
    return tables_dict
if __name__=='__main__':
    html_file='sample.html'
    result=read_html_to_dict(html_file)
    print(result)


{'Tables_1': {'Name': ['Alice', 'Bob'], 'Age': [24, 27]}, 'Tables_2': {'Country': ['France', 'India'], 'Capital': ['Paris', 'Delhi']}}
